using UnityEngine;

public class PlayerController : MonoBehaviour
{
    // РЬ НКХЉИГЦЎРЧ РЮНКХЯНКИІ РњРхЧЯДТ static КЏМі
    public static PlayerController instance;

    // ЧУЗЙРЬОюРЧ ДйИЅ ФФЦїГЭЦЎЕщРЛ ПЌАсЧв КЏМіЕщ
    private PlayerInput playerInput;
    private PlayerMovement playerMovement;
    private CharacterStats myStats; // РкНХРЧ НКХШ СЄКИ
    private Animator animator; // Animator ФФЦїГЭЦЎ ТќСЖ

    private Transform currentTarget; // ЧіРч УпРћ/АјАн СпРЮ ДыЛѓ
    private float lastAttackTime; // ИЖСіИЗ АјАн НУАЃ


    void Awake()
    {
        // 1. instanceАЁ ОЦСї МГСЄЕЧСі ОЪОвДйИщ (УжУЪРЧ ЧУЗЙРЬОюЖѓИщ)
        if (instance == null)
        {
            // instanceПЁ РкБт РкНХРЛ ЧвДч
            instance = this;
            // ОРРЬ РќШЏЕЧОюЕЕ РЬ АдРг ПРКъСЇЦЎИІ ЦФБЋЧЯСі ОЪЕЕЗЯ МГСЄ
            DontDestroyOnLoad(gameObject);
        }
        // 2. instanceАЁ РЬЙЬ СИРчЧбДйИщ (ОРРЛ ЕЧЕЙОЦПЭМ­ Л§Бф КЙСІЧАРЬЖѓИщ)
        else
        {
            // РЬ АдРг ПРКъСЇЦЎ(КЙСІЧА)ИІ ЦФБЋ
            Destroy(gameObject);
        }

        // РкБт РкНХПЁАд КйОюРжДТ ДйИЅ НКХЉИГЦЎЕщРЛ РкЕПРИЗЮ УЃОЦ ПЌАс
        playerInput = GetComponent<PlayerInput>();
        playerMovement = GetComponent<PlayerMovement>();
        myStats = GetComponent<CharacterStats>();
        animator = GetComponent<Animator>(); // Animator ПЌАс
    }

    void Update()
    {
        // 1. ЛѕЗЮПю ХЌИЏРЬ ЙпЛ§ЧпРЛ ЖЇ
        if (playerInput.IsNewClick)
        {
            // 1-1. АјАн ДыЛѓРЬ СіСЄЕЧОњДйИщ
            if (playerInput.CombatTarget != null)
            {
                currentTarget = playerInput.CombatTarget;
            }
            // 1-2. ЙйДкРЛ ХЌИЏЧпДйИщ (РЬЕП)
            else
            {
                currentTarget = null; // ХИАй ЧиСІ
                playerMovement.MoveTo(playerInput.TargetPosition);
            }
        }

        // 2. АјАн ДыЛѓРЬ РжДйИщ
        if (currentTarget != null)
        {
            float distance = Vector3.Distance(transform.position, currentTarget.position);

            // 2-1. ЛчАХИЎ ЙлРЬИщ, ДыЛѓПЁАд РЬЕП
            if (distance > myStats.AttackRange)
            {
                playerMovement.MoveTo(currentTarget.position);
            }
            // 2-2. ЛчАХИЎ ОШРЬИщ, РЬЕПРЛ ИиУпАэ АјАн
            else
            {
                // РЬЕП СЄСі (ЧіРч РЇФЁИІ ИёЧЅЗЮ МГСЄ)
                playerMovement.MoveTo(transform.position);

                // АјАн Ф№ДйПюРЬ СіГЕДйИщ АјАн
                if (Time.time >= lastAttackTime + myStats.AttackCooldown)
                {
                    Attack(currentTarget);
                    lastAttackTime = Time.time;
                }
            }
        }

        void Attack(Transform target)
        {
            CharacterStats targetStats = target.GetComponent<CharacterStats>();
            if (targetStats != null)
            {
                Debug.Log($"{name}РЬ(АЁ) {target.name}РЛ(ИІ) АјАн!");
                animator.SetTrigger("DoAttack");
                targetStats.TakeDamage(myStats.AttackPower);

                // АјАнЧб ДыЛѓРЬ ИѓНКХЭЖѓИщ, ИѓНКХЭПЁАд АјАнЙоОвДйАэ ОЫЗССжБт
                MonsterWanderAI monsterAI = target.GetComponent<MonsterWanderAI>();
                if (monsterAI != null)
                {
                    monsterAI.OnAttacked(transform); // 'ГЊ(ЧУЗЙРЬОю)'ИІ АјАнРкЗЮ ОЫИВ
                }
            }
        }


    }
}