using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    public float moveSpeed = 5f;

    public bool IsMoving { get; private set; } // ОжДЯИоРЬХЭАЁ ТќАэЧв ЛѓХТ
    public Vector3 TargetPosition { get; private set; }

    void Start()
    {
        // НУРлЧв ЖЉ ПђСїРЬСі ОЪРИЙЧЗЮ ЧіРч РЇФЁИІ ИёЧЅЗЮ МГСЄ
        TargetPosition = transform.position;
    }

    void Update()
    {
        // ИёЧЅ РЇФЁПЭ ЧіРч РЇФЁРЧ АХИЎАЁ 0.01КИДй ХЉИщ ПђСїРЬДТ Сп
        if (Vector3.Distance(transform.position, TargetPosition) > 0.01f)
        {
            transform.position = Vector3.MoveTowards(transform.position, TargetPosition, moveSpeed * Time.deltaTime);
            IsMoving = true;
        }
        else
        {
            IsMoving = false;
        }
    }

    // PlayerControllerАЁ ШЃУтЧв АјАГ ЧдМі
    public void MoveTo(Vector3 destination)
    {
        TargetPosition = destination;
    }
}